"""Fixed foreing keys type to bigint

Revision ID: cf19a32bf645
Revises: 4846da6b976f
Create Date: 2025-08-27 13:18:17.208638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf19a32bf645'
down_revision: Union[str, Sequence[str], None] = '4846da6b976f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embedded_chunks",
        "document_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        "tokenized_chunks",
        "document_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embedded_chunks",
        "document_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        "tokenized_chunks",
        "document_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
