"""Added table for prompts

Revision ID: 3294f1940552
Revises: cf19a32bf645
Create Date: 2025-08-29 11:56:52.459160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3294f1940552'
down_revision: Union[str, Sequence[str], None] = 'cf19a32bf645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key', name='uq_prompts_tkey')
    )
    op.create_index(op.f('ix_prompts_template_key'), 'prompts', ['template_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_template_key'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
