"""Fixed type for users' password_hash

Revision ID: 2c6e62fe0b30
Revises: 804f5fcf92bf
Create Date: 2025-09-07 19:53:31.171066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6e62fe0b30'
down_revision: Union[str, Sequence[str], None] = '804f5fcf92bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('users', sa.Column('password_hash', sa.LargeBinary, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('users', sa.Column('password_hash', sa.String(255), nullable=False))
    # ### end Alembic commands ###
