"""Changed chunks and documents props

Revision ID: 5c786914f584
Revises: 19bfec9ffdbf
Create Date: 2025-09-01 16:02:36.910809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c786914f584'
down_revision: Union[str, Sequence[str], None] = '19bfec9ffdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_embedded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('is_tokenized', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('embedded_chunks', sa.Column('start_index', sa.BigInteger(), nullable=False))
    op.add_column('embedded_chunks', sa.Column('end_index', sa.BigInteger(), nullable=False))
    op.add_column('embedded_chunks', sa.Column('serial_idx', sa.Integer(), nullable=False))
    op.drop_column('embedded_chunks', 'index')
    op.add_column('tokenized_chunks', sa.Column('start_index', sa.BigInteger(), nullable=False))
    op.add_column('tokenized_chunks', sa.Column('end_index', sa.BigInteger(), nullable=False))
    op.add_column('tokenized_chunks', sa.Column('serial_idx', sa.Integer(), nullable=False))
    op.drop_column('tokenized_chunks', 'index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokenized_chunks', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tokenized_chunks', 'serial_idx')
    op.drop_column('tokenized_chunks', 'end_index')
    op.drop_column('tokenized_chunks', 'start_index')
    op.add_column('embedded_chunks', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('embedded_chunks', 'serial_idx')
    op.drop_column('embedded_chunks', 'end_index')
    op.drop_column('embedded_chunks', 'start_index')
    op.drop_column('documents', 'is_tokenized')
    op.drop_column('documents', 'is_embedded')
    # ### end Alembic commands ###
