"""create tables for chunks' vectors and tokens

Revision ID: ecef875da485
Revises: 9159ed20e205
Create Date: 2025-09-22 03:36:27.185717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecef875da485'
down_revision: Union[str, Sequence[str], None] = '9159ed20e205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_tokens',
    sa.Column('tokens', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name='fk_chunk_tokens_chunk_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_vector',
    sa.Column('vector', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name='fk_chunk_vector_chunk_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_vector')
    op.drop_table('chunk_tokens')
    # ### end Alembic commands ###
