"""Added relationship between users and documents

Revision ID: 804f5fcf92bf
Revises: fed4033f1e07
Create Date: 2025-09-07 16:06:11.390986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '804f5fcf92bf'
down_revision: Union[str, Sequence[str], None] = 'fed4033f1e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key('fk_document_user_id', 'documents', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'isActive')
    op.drop_constraint('fk_document_user_id', 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
