"""Changed indexes in chunk tables

Revision ID: 19bfec9ffdbf
Revises: 3294f1940552
Create Date: 2025-08-30 21:03:22.993101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bfec9ffdbf'
down_revision: Union[str, Sequence[str], None] = '3294f1940552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedded_chunks', sa.Column('index', sa.Integer(), nullable=False))
    op.drop_column('embedded_chunks', 'end_index')
    op.drop_column('embedded_chunks', 'start_index')
    op.add_column('tokenized_chunks', sa.Column('index', sa.Integer(), nullable=False))
    op.drop_column('tokenized_chunks', 'end_index')
    op.drop_column('tokenized_chunks', 'start_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokenized_chunks', sa.Column('start_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tokenized_chunks', sa.Column('end_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('tokenized_chunks', 'index')
    op.add_column('embedded_chunks', sa.Column('start_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('embedded_chunks', sa.Column('end_index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('embedded_chunks', 'index')
    # ### end Alembic commands ###
