"""Changed tokens type in TokenizedChunk

Revision ID: fed4033f1e07
Revises: 06801f22965a
Create Date: 2025-09-03 00:11:19.918210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fed4033f1e07'
down_revision: Union[str, Sequence[str], None] = '06801f22965a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE tokenized_chunks
            ALTER COLUMN tokens TYPE INTEGER[]
            USING ARRAY[]::INTEGER[];
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE tokenized_chunks
            ALTER COLUMN tokens TYPE VARCHAR[]
            USING ARRAY[]::VARCHAR[];
        """)
    # ### end Alembic commands ###
