"""Added names for constraints

Revision ID: 4846da6b976f
Revises: d2c91eb51f76
Create Date: 2025-08-27 13:14:15.543552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4846da6b976f'
down_revision: Union[str, Sequence[str], None] = 'd2c91eb51f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedded_chunks', 'start_index',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('embedded_chunks', 'end_index',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tokenized_chunks', 'start_index',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tokenized_chunks', 'end_index',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.alter_column('tokenized_chunks', 'end_index',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('tokenized_chunks', 'start_index',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('embedded_chunks', 'end_index',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('embedded_chunks', 'start_index',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
