"""add file storage fields for documents

Revision ID: 83cedfad127a
Revises: ecef875da485
Create Date: 2026-01-03 20:24:35.627630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cedfad127a'
down_revision: Union[str, Sequence[str], None] = 'ecef875da485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_object_key', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('media_type', sa.String(length=100), nullable=False))
    op.alter_column('documents', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'documents', ['s3_object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'media_type')
    op.drop_column('documents', 's3_object_key')
    # ### end Alembic commands ###
